# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=b''),
        ),
    ]
